---
title: "Time Series - Covid-19Proj"
author: "Tai Chowdhury and Simerpreet Kaur"
date: "3/27/2021"
output: html_document
---

# Datasets:
1) All Covid
2) Post Vaccine

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
All_Covid <- read_csv("All_Covid.csv")

Post_Vaccine <- read_csv("Post_Vaccine.csv")


```



#############
#### EDA ####
#############

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# All Covid Data
plotts.wge(All_Covid$new_cases_per_million)
plotts.wge(All_Covid$icu_patients_per_million)
plotts.wge(All_Covid$hosp_patients_per_million)
plotts.wge(All_Covid$new_vaccinations_smoothed_per_million)
plotts.wge(All_Covid$new_deaths_per_million)

# Post Vaccine
plotts.wge(Post_Vaccine$new_cases_per_million)
plotts.wge(Post_Vaccine$icu_patients_per_million)
plotts.wge(Post_Vaccine$hosp_patients_per_million)
plotts.wge(Post_Vaccine$new_vaccinations_smoothed_per_million)
plotts.sample.wge(Post_Vaccine$new_deaths_per_million)

```


#### ARIMA Model 1 (with seasonal 1-b^7 term)


```{r pressure, echo=FALSE}

#Check for white noise
plotts.sample.wge(Post_Vaccine$new_deaths_per_million) #Damped sinusoudal behavior in ACF, also indication of seasonality

# Estimate a model by overfittting:
diff_s7 <- artrans.wge(Post_Vaccine$new_deaths_per_million, 7)
est_m1_1 = est.ar.wge(Post_Vaccine$new_deaths_per_million, p = 10, type = 'burg')

#search for p,q as per lower AIC score
aic5.wge(Post_Vaccine$new_deaths_per_million) # CONCERN: picks 5,1 vs 4,1

#Estimation for final model:

m1_arma = est.arma.wge(diff_s7, p = 5, q = 1)
mean(Post_Vaccine$new_deaths_per_million) #7.093083

fore_m1_short = fore.arma.wge(Post_Vaccine$new_deaths_per_million, phi = m1_arma$phi, theta = m1_arma$theta)
For_ase_m1_short = mean((fore_m1_short$f - Post_Vaccine$new_deaths_per_million[(95-10+1):95])^2)
For_ase_m1_short #1.77

Rolling_Window_ASE(Post_Vaccine$new_deaths_per_million, trainingSize = 70, horizon = 5, d = 1, phi = m1_arma$phi, theta = m1_arma$theta,s= 7)#5.392431


## Colored Plot for short term
plot(as.numeric(Post_Vaccine$new_deaths_per_million), type = "l", xlim = c(1,96))
lines(seq(87,96,1),m3_forcast_short$f  , col = "red")
seq
## Colored Plot for long term
plot(as.numeric(Post_Vaccine$new_deaths_per_million), type = "l", xlim = c(1,136))
lines(seq((136-40+1),136,1),m3_forcast_long_40$f, col = "red")

```

#### ARMA MODEL 2 - (with differencing = 1, (5,2))  ####


```{r pressure, echo=FALSE}

m2_dif1 = artrans.wge(Post_Vaccine$new_deaths_per_million,1)

# Estimate a model by overfittting:

est_m1_2 = est.ar.wge(Post_Vaccine$new_deaths_per_million, p = 8, type = 'burg') # It contains (1-B) as 

#search for p,q as per lower AIC score
aic5.wge(m2_dif1) #picks 5,2

#Estimation for final model:

m2_arma = est.arma.wge(m2_dif1, p = 5, q = 2)
mean(Post_Vaccine$new_deaths_per_million) #7.093083

fore_m2_short = fore.arma.wge(Post_Vaccine$new_deaths_per_million, phi = m2_arma$phi, theta = m2_arma$theta)
For_ase_m2_short = mean((fore_m2_short$f - Post_Vaccine$new_deaths_per_million[(95-10+1):95])^2)
For_ase_m2_short #1.77

## Colored Plot for short term
plot(as.numeric(Post_Vaccine$new_deaths_per_million), type = "l", xlim = c(1,96))
lines(seq(87,96,1),m4_forcast_short$f  , col = "red")



```


#### ARIMA - (with (4,1) seanality )  ####


```{r pressure, echo=FALSE}

m2_dif1 = artrans.wge(Post_Vaccine$new_deaths_per_million,1)

# Estimate a model by overfittting:

est_m1_2 = est.ar.wge(Post_Vaccine$new_deaths_per_million, p = 8, type = 'burg') # It contains (1-B) as 

#search for p,q as per lower AIC score
aic5.wge(m2_dif1) #picks 5,2

#Estimation for final model:

m2_arma = est.arma.wge(m2_dif1, p = 5, q = 2)
mean(Post_Vaccine$new_deaths_per_million) #7.093083

fore_m2_short = fore.arma.wge(Post_Vaccine$new_deaths_per_million, phi = m2_arma$phi, theta = m2_arma$theta)
For_ase_m2_short = mean((fore_m2_short$f - Post_Vaccine$new_deaths_per_million[(95-10+1):95])^2)
For_ase_m2_short #1.77

## Colored Plot for short term
plot(as.numeric(Post_Vaccine$new_deaths_per_million), type = "l", xlim = c(1,96))
lines(seq(87,96,1),m4_forcast_short$f  , col = "red")



```

#### Multivariate  (No Trend) ####



```{r pressure, echo=FALSE}
# Explanatory Variable
expvar_vaccine = data.frame(Post_Vaccine$new_cases_per_million, Post_Vaccine$icu_patients_per_million,
                         Post_Vaccine$hosp_patients_per_million,Post_Vaccine$new_vaccinations_smoothed_per_million)

# All data with no lag and no trend
covfit1=lm(new_deaths_per_million~ new_cases_per_million+icu_patients_per_million+hosp_patients_per_million
          +new_vaccinations_smoothed_per_million, data = Post_Vaccine)
AIC(covfit1)#425.1261
summary(covfit1) # new_vaccinations_smoothed_per_million  2.213e-05  2.587e-04   0.086    0.932 

deathrate_res= is.numeric(aic.wge(covfit1$residuals,p=0:10, q=0))  # AIC picks p=9

acf(covfit1$residuals)

fit1=arima(Post_Vaccine$new_deaths_per_million,order=c(9,0,0),xreg=expvar_vaccine)
fit1
AIC(fit1) #323.68

acf(fit1$residuals) # looks like white noise behavior
ltest = ljung.wge(fit$resid)
ltest$pval


# ASE for model with no lag and no trend (last 5)
Post_Vaccine2 = Post_Vaccine[1:91,]

expvar_vaccine2 = data.frame(Post_Vaccine2$new_cases_per_million, Post_Vaccine2$icu_patients_per_million,
                         Post_Vaccine2$hosp_patients_per_million,Post_Vaccine2$new_vaccinations_smoothed_per_million)

covidfit2_mi=lm(new_deaths_per_million~ new_cases_per_million+icu_patients_per_million+hosp_patients_per_million
          +new_vaccinations_smoothed_per_million, data = Post_Vaccine2)
AIC(covidfit2_mi) #402.9405

M1_final_res=aic.wge(covidfit2_mi$residuals,p=0:10, q=0)  # AIC picks p=9
fit2_m1=arima(Post_Vaccine2$new_deaths_per_million,order=c(9,0,0),xreg=cbind(Post_Vaccine2$new_cases_per_million, Post_Vaccine2$icu_patients_per_million,Post_Vaccine2$hosp_patients_per_million, Post_Vaccine2$new_vaccinations_smoothed_per_million))
fit2_m1
AIC(fit2_m1) #312.61

preds1 = predict(fit2_m1, newxreg = cbind(Post_Vaccine$new_cases_per_million[92:96], Post_Vaccine$icu_patients_per_million[92:96],Post_Vaccine$hosp_patients_per_million[92:96], Post_Vaccine$new_vaccinations_smoothed_per_million[92:96]))
ASE1 = mean((Post_Vaccine$new_deaths_per_million[92:96] - preds1$pred)^2)
ASE1 #1.332711


## Colored Plot for short term  NEEDS WORK
plot(as.numeric(Post_Vaccine$new_deaths_per_million), type = "l", xlim = c(1,96))
lines(seq(87,96,1),m4_forcast_short$f  , col = "red")



```


#### Multivariate  ( Trend added, no lag ) ####



```{r pressure, echo=FALSE}
#with trend

# ASE for model with no lag and trend (last 5)
t=1:96
Post_Vaccine$t = t
Post_Vaccine2 = Post_Vaccine[1:91,]
covidfit2_m2=lm(new_deaths_per_million~ t+ new_cases_per_million+icu_patients_per_million+hosp_patients_per_million
          +new_vaccinations_smoothed_per_million, data = Post_Vaccine2)
AIC(covidfit2_m2) #401.7352

M2_final_res=aic.wge(covidfit2_m2$residuals,p=0:10, q=0)  # AIC picks p=9
fit2_m2=arima(Post_Vaccine2$new_deaths_per_million,order=c(9,0,0),xreg=cbind(Post_Vaccine2$new_cases_per_million, Post_Vaccine2$icu_patients_per_million,Post_Vaccine2$hosp_patients_per_million, Post_Vaccine2$new_vaccinations_smoothed_per_million))
fit2_m2
AIC(fit2_m2) #312.6069, not much of a change from previous trend

# Predictions with trend
preds2 = predict(fit2_m2, newxreg = cbind(Post_Vaccine$new_cases_per_million[92:96], Post_Vaccine$icu_patients_per_million[92:96],Post_Vaccine$hosp_patients_per_million[92:96], Post_Vaccine$new_vaccinations_smoothed_per_million[92:96]))
ASE2 = mean((Post_Vaccine$new_deaths_per_million[92:96] - preds2$pred)^2)
ASE2 #1.332711

```


#### Multivariate  ( Adding Lags ) ####



```{r pressure, echo=FALSE}

#Lagging Post Vaccine variables
ccf(Post_Vaccine$new_deaths_per_million,Post_Vaccine$new_cases_per_million)
ccf(Post_Vaccine$new_deaths_per_million,Post_Vaccine$icu_patients_per_million)
ccf(Post_Vaccine$new_deaths_per_million,Post_Vaccine$hosp_patients_per_million)
ccf(Post_Vaccine$new_deaths_per_million,Post_Vaccine$new_vaccinations_smoothed_per_million)

new_cases_per_million1 = dplyr::lag(Post_Vaccine$new_cases_per_million,1)
icu_patients_per_million1 = dplyr::lag(Post_Vaccine$icu_patients_per_million,1)
hosp_patients_per_million1 = dplyr::lag(Post_Vaccine$hosp_patients_per_million,1)
new_vaccinations_smoothed_per_million1 = dplyr::lag(Post_Vaccine$new_vaccinations_smoothed_per_million,1)

Post_Vaccine$new_cases_per_million1 = new_cases_per_million1
Post_Vaccine$icu_patients_per_million1 = icu_patients_per_million1
Post_Vaccine$hosp_patients_per_million1 = hosp_patients_per_million1
Post_Vaccine$new_vaccinations_smoothed_per_million1 = new_vaccinations_smoothed_per_million1

# ASE for model3
t=1:96
Post_Vaccine$t = t
Post_Vaccine2 = Post_Vaccine[1:91,]
covidfit3_m3=lm(new_deaths_per_million~ t+ new_cases_per_million1+icu_patients_per_million1+hosp_patients_per_million1
          +new_vaccinations_smoothed_per_million1, data = Post_Vaccine2)
AIC(covidfit3_m3) #422.46

M3_final_res=aic.wge(covidfit3_m3$residuals,p=0:10, q=0)  # AIC picks p=9
fit3_m3=arima(Post_Vaccine2$new_deaths_per_million,order=c(9,0,0),xreg=cbind(Post_Vaccine2$new_cases_per_million1, Post_Vaccine2$icu_patients_per_million1,Post_Vaccine2$hosp_patients_per_million1, Post_Vaccine2$new_vaccinations_smoothed_per_million1))
fit3_m3
AIC(fit3_m3) #321.61

# Predictions with lags
preds3 = predict(fit3_m3, newxreg = cbind(Post_Vaccine$new_cases_per_million[92:96], Post_Vaccine$icu_patients_per_million[92:96],Post_Vaccine$hosp_patients_per_million[92:96], Post_Vaccine$new_vaccinations_smoothed_per_million[92:96]))
ASE3 = mean((Post_Vaccine$new_deaths_per_million[92:96] - preds3$pred)^2)
ASE3 #2.97754



```



#### Forecast Features ####



```{r pressure, echo=FALSE}


ests_newc = aic.wge(Post_Vaccine$new_cases_per_million)
est_new_case = est.arma.wge(Post_Vaccine$new_cases_per_million,p = 5, q = 1)
Fore_newcase = fore.arma.wge(Post_Vaccine$new_cases_per_million,phi = est_new_case$phi, theta = est_new_case$theta, n.ahead = 5)


ests_icu = aic.wge(Post_Vaccine$icu_patients_per_million) #picks 2,1
est_icu = est.arma.wge(Post_Vaccine$icu_patients_per_million,p = 2, q = 1)
Fore_icu = fore.arma.wge(Post_Vaccine$icu_patients_per_million,phi = est_icu$phi, theta = est_icu$theta, n.ahead = 5)

ests_hosp = aic.wge(Post_Vaccine$hosp_patients_per_million) #picks 2,1
est_hosp = est.arma.wge(Post_Vaccine$hosp_patients_per_million,p = 2, q = 1)
Fore_hos = fore.arma.wge(Post_Vaccine$hosp_patients_per_million,phi = est_hosp$phi, theta = est_hosp$theta, n.ahead = 5)

ests_vaccine = aic.wge(Post_Vaccine$new_vaccinations_smoothed_per_million) #picks 3,1
est_vaccine = est.arma.wge(Post_Vaccine$new_vaccinations_smoothed_per_million,p = 3, q = 1)
Fore_vaccine = fore.arma.wge(Post_Vaccine$new_vaccinations_smoothed_per_million,phi = est_vaccine$phi, theta = est_vaccine$theta, n.ahead = 5)

aic5.wge(BSales$ad_online, p = 0:10)
est_online = est.arma.wge(BSales$ad_online,p = 6)
dev.off()
plot.ts(BSales$ad_online[1:100])
ad_onlineFORECAST = fore.arma.wge(BSales$ad_online,phi = est_online$phi, n.ahead = 6)



```

#### with trend and lagging ####



```{r pressure, echo=FALSE}

Fore_newcase1 = lag(Fore_newcase,1)
Fore_icu1 = lag(Fore_icu,1)
Fore_hos1 = lag(Fore_hos,1)
Fore_vaccine1 = lag(Fore_vaccine,1)

t=1:96
Post_Vaccine$t = t
Post_Vaccine2 = Post_Vaccine[1:91,]
covidfit4_m4=lm(new_deaths_per_million~ t+ new_cases_per_million1+icu_patients_per_million1+hosp_patients_per_million1
          +new_vaccinations_smoothed_per_million1, data = Post_Vaccine2)
AIC(covidfit4_m4) #422.4621

preds4 = predict(covidfit4_m4, newxreg = cbind(Fore_newcase1$f[1:5],Fore_icu1$f[1:5],Fore_hos1$f, Fore_vaccine1$f, Post_Vaccine$t[96:100]))
ASE4 = mean((Post_Vaccine$new_deaths_per_million - preds4$ [1:5])^2)
ASE4 #13.06587

preds4$pred

```






















































